services:
  web:
    build: !reset null
    image: ghcr.io/logplace/logplace-web:latest
    ports: !reset []
    deploy:
      mode: replicated
      replicas: 3
    labels:
      - "traefik.http.services.web.loadbalancer.server.port=3000"
      - "traefik.http.routers.web.rule=Host(`logplace.xyz`)"

  reverse-proxy:
    image: traefik:v3.1
    command:
      - "--api.insecure=true"
      - "--providers.docker"
    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefil can listen to Docker events
      - /var/run/docker.sock:/var/run/docker.sock
