services:
  db:
    image: postgres
    env_file: .env.docker-compose
    volumes:
      - capsulr-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    env_file: .env.docker-compose
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy

volumes:
  capsulr-data:
