import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Provider as TrpcProvider } from "./_trpc/Provider";
import { Theme } from "@radix-ui/themes";
import { Toaster } from "./Toaster";
import { Headerbar } from "./Headerbar";
import { Suspense } from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Suspense>
          <Toaster />
        </Suspense>
        <Theme accentColor="iris" grayColor="slate">
          <TrpcProvider>
            <div className="relative flex flex-row min-h-screen justify-center text-gray-10">
              <Headerbar />
              <div className="flex flex-row justify-center pt-[64px] w-full md:w-[50%] lg:w-[40%] min-h-screen border-[1px] border-gray-3">
                <div className="w-full p-4">{children}</div>
              </div>
            </div>
          </TrpcProvider>
        </Theme>
      </body>
    </html>
  );
}
