import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Provider as TrpcProvider } from "./_trpc/Provider";
import { Theme } from "@radix-ui/themes";
import { Toaster } from "./Toaster";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased text-gray-11`}
      >
        <Toaster />
        <Theme accentColor="iris" grayColor="slate">
          <TrpcProvider>{children}</TrpcProvider>
        </Theme>
      </body>
    </html>
  );
}
